version: '3.8'

services:
  # Spring Boot 애플리케이션
  app:
    build: .
    container_name: carelink-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=${DB_URL:-jdbc:mysql://db:3306/carelink?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-mysql}
      - KAKAO_APP_KEY=${KAKAO_APP_KEY:-0948e3e4faa457fb6083f68e1ce10458}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY:-0948e3e4faa457fb6083f68e1ce10458}
      - UPLOAD_BASE_PATH=${UPLOAD_BASE_PATH:-/carelink-uploads/}
    volumes:
      - carelink-uploads:/carelink-uploads
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - carelink-network

  # MySQL 데이터베이스
  db:
    image: mysql:8.0
    container_name: carelink-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-carelink}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-mysql}
      - TZ=Asia/Seoul
    volumes:
      - carelink-db-data:/var/lib/mysql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1.schema.sql
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    networks:
      - carelink-network

volumes:
  carelink-uploads:
    name: carelink-uploads
  carelink-db-data:
    name: carelink-db-data

networks:
  carelink-network:
    name: carelink-network 