[variables]
NIXPACKS_JDK_VERSION = "11"
NIXPACKS_GRADLE_VERSION = "8.13"

providers = ["java"]

[phases.setup]
nixPkgs = ["..."]

[phases.build]
cmds = ["chmod +x gradlew", "./gradlew clean build -x test"]

[start]
cmd = "java -jar build/libs/carelink-0.0.1-SNAPSHOT.jar"