[variables]
NIXPACKS_JDK_VERSION = "11"

[phases.setup]
nixPkgs = ["openjdk11", "gradle"]

[phases.build] 
cmds = [
    "chmod +x gradlew",
    "./gradlew clean build -x test --no-daemon"
]

[start]
cmd = "java -Xmx300m -XX:+UseG1GC -XX:+UseStringDeduplication -Dspring.profiles.active=production -jar build/libs/carelink-0.0.1-SNAPSHOT.jar"