[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# 환경변수
[env]
PORT = "8080"
SPRING_PROFILES_ACTIVE = "railway"
JAVA_VERSION = "11"