[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/actuator/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# 환경변수 기본값 설정
[env]
PORT = "8080"
SPRING_PROFILES_ACTIVE = "railway"
JAVA_VERSION = "11"
GRADLE_OPTS = "-Xmx2g"

# Nixpacks 빌드 설정 제거 - Railway 기본값 사용