[build]
builder = "nixpacks"
nixpacksPlan = "jdk11 gradle"
buildCommand = "chmod +x ./gradlew && ./gradlew build -x test"

[deploy]
startCommand = "java -Xms512m -Xmx1024m -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -Dserver.port=$PORT -jar build/libs/carelink-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10