# 개발 환경 설정
spring:
    
  # 개발 중 편의 설정
  thymeleaf:
    cache: false # 템플릿 캐시 비활성화
    
  # 보안 디버그 모드
  security:
    debug: true
    
  # 로그 레벨 (개발 환경)
logging:
  level:
    com.example.carelink: DEBUG
    org.springframework.security: DEBUG
    
# 개발 환경 전용 설정
server:
  error:
    include-stacktrace: always # 에러 스택트레이스 표시