# 운영 환경 설정
spring:
    
  # 운영 환경 성능 최적화
  thymeleaf:
    cache: true # 템플릿 캐시 활성화
    
  # 보안 강화
  security:
    debug: false
    
  # 정적 리소스 캐싱
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 3600 # 1시간 캐시
          
# 운영 환경 로그 설정
logging:
  level:
    com.example.carelink: INFO
    org.springframework.security: WARN
    
# 운영 환경 보안 설정
server:
  error:
    include-stacktrace: never # 에러 스택트레이스 숨김
    include-message: never # 에러 메시지 숨김