# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /

# 데이터베이스 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/carelink?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: mysql
    
  # Thymeleaf 설정
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false  # 개발 단계에서는 캐시 비활성화
    
  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# MyBatis 설정
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.carelink.dto

# 로깅 설정
logging:
  level:
    com.example.carelink: DEBUG
    org.springframework.web: DEBUG
    org.mybatis: DEBUG

#사용자 프로필 사진을 서버 컴퓨터의 C:/uploads/profile_images/ 폴더에 저장
file:
  upload-dir:
    profile: C:/uploads/profile_images/